version: "3"
services:
  db:
    image: mysql:5.7
    container_name: crawl
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: trading
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER : "sj"
      MYSQL_PASSWORD : 1234
      
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)
      - ./init:/docker-entrypoint-initdb.d